name: termo-service
channels:
  - conda-forge
dependencies:
  - bzip2=1.0.8
  - ca-certificates=2025.8.3
  - icu=75.1
  - libexpat=2.7.1
  - libffi=3.4.6
  - liblzma=5.8.1
  - libmpdec=4.0.0
  - libsqlite=3.50.4
  - libzlib=1.3.1
  - ncurses=6.5
  - openssl=3.5.2
  - pip=25.2
  - python=3.13.5
  - python_abi=3.13
  - readline=8.2
  - tk=8.6.13
  - tzdata=2025b
  - pip:
    - PyYAML==6.0.2
    - appdirs==1.4.4
    - bleak==1.1.0
    - corefile==0.1.11
    - corelog==0.0.20
    - corestring==0.3.18
    - corethread==0.1.3
    - fastapi==0.116.1
    - firebase_admin==7.1.0
    - humanfriendly==10.0
    - peewee==3.18.2
    - psutil==7.0.0
    - psycopg2==2.9.10
    - psycopg2-binary==2.9.10
    - typer==0.16.1
    - uvicorn==0.35.0
    - uvloop==0.21.0
    - websockets==15.0.1

prefix: "/Volumes/Devo/Users/jago/miniforge3/envs/termo-service"
